"""engine.py — RiskEngine coordinator.

Wires together all risk mixins and owns the lifecycle (start/stop/loop).
Do NOT edit this file for check/exit/portfolio logic — use the dedicated module.

  Per-trade checks    →  backend/risk/checks.py
  Exit mechanics      →  backend/risk/exit_trigger.py
  Dashboard / manual  →  backend/risk/portfolio.py
"""

import threading
import time
import logging
from typing import Optional, Callable

from backend.risk.checks       import RiskChecksMixin
from backend.risk.exit_trigger import RiskExitMixin
from backend.risk.portfolio    import RiskPortfolioMixin

log = logging.getLogger("risk_engine")

CHECK_INTERVAL = 1.0   # seconds between risk checks


class RiskEngine(RiskChecksMixin, RiskExitMixin, RiskPortfolioMixin):

    def __init__(self):
        self._running = False
        self._thread: Optional[threading.Thread] = None
        # Injected by live execution module; called after each DB exit
        self._exit_callback: Optional[Callable] = None

    def register_exit_callback(self, fn: Callable):
        """
        Live execution module calls this once at startup.
        Signature: fn(trade_id, exit_price, reason, env)
        """
        self._exit_callback = fn

    # ── Lifecycle ──────────────────────────────────────────────────────────────

    def start(self):
        if self._running:
            return
        self._running = True
        self._thread  = threading.Thread(target=self._loop, daemon=True, name="RiskEngine")
        self._thread.start()
        log.info("[RISK] Engine started.")
        print("[RISK] Engine started.")

    def stop(self):
        self._running = False
        log.info("[RISK] Engine stopped.")
        print("[RISK] Engine stopped.")

    def _loop(self):
        while self._running:
            try:
                self._run_checks()
            except Exception as e:
                log.error(f"[RISK] Loop error: {e}")
                print(f"[RISK] Loop error: {e}")
            time.sleep(CHECK_INTERVAL)


# ── Singleton ──────────────────────────────────────────────────────────────────
risk_engine = RiskEngine()
