"""strategy.py — OpeningBreakout coordinator.

Wires together all OB mixins into one class. This file owns the lifecycle
(start/stop/tick) and the public API (get_plan/get_state).

Do NOT edit this file for filter/entry/management/tuning changes — use the dedicated module.
"""

import threading
import time
from dataclasses import asdict
from datetime import datetime
from typing import Dict, Optional

from backend.core.market_state      import market
from backend.core.settings_manager  import is_live_mode
from backend.core.session_manager   import check_portfolio_sl, set_selected_stocks

from backend.database import TradeEnv

from backend.strategies.ob.params  import (
    SCAN_START, EARLY_ENTRY_FROM, PREVIEW_FROM, SCAN_END,
    ENTRY_DEADLINE, ENTRY_HARD_DEADLINE, SQUARE_OFF, LOOP_SEC,
)
from backend.strategies.ob.params   import OBParamsMixin
from backend.strategies.ob.filters  import OBFiltersMixin
from backend.strategies.ob.state    import OBStateMixin
from backend.strategies.ob.entry    import OBEntryMixin
from backend.strategies.ob.manage   import OBManageMixin
from backend.strategies.ob.exit     import OBExitMixin
from backend.strategies.ob.tuner    import OBTunerMixin


class OpeningBreakout(OBParamsMixin, OBFiltersMixin, OBStateMixin,
                       OBEntryMixin, OBManageMixin, OBExitMixin, OBTunerMixin):

    def __init__(self):
        self._running  = False
        self._thread: Optional[threading.Thread] = None
        self._enabled  = True
        self._today    = None
        self._open_ref: Dict[str, float] = {}
        self._open_ref_final: set = set()
        self._plan = None
        self._phase = "IDLE"
        self._params = self._load_params()
        self._last_tune: Optional[str] = None
        self._tune_report: dict = {}

    # ── Lifecycle ─────────────────────────────────────────────────────────────

    def start(self):
        if self._running:
            return
        self._running = True
        self._thread = threading.Thread(target=self._loop, daemon=True, name="OpeningBreakout")
        self._thread.start()
        print("[OB] Opening Breakout strategy started.")

    def stop(self):
        self._running = False

    def set_enabled(self, on: bool):
        self._enabled = on

    def _loop(self):
        while self._running:
            try:
                self._tick()
            except Exception as e:
                print(f"[OB] tick error: {e}")
            time.sleep(LOOP_SEC)

    # ── Per-tick state machine ────────────────────────────────────────────────

    def _tick(self):
        now = datetime.now()
        t   = now.time()

        if self._today != now.date():
            self._today = now.date()
            self._open_ref.clear()
            self._open_ref_final.clear()
            self._plan  = None
            self._phase = "IDLE"

        if not self._enabled or not market.is_feed_connected():
            return

        env = TradeEnv.LIVE if is_live_mode() else TradeEnv.PAPER

        if check_portfolio_sl(env):
            self._phase = "KILLED"
            return

        if t >= SQUARE_OFF:
            if self._phase != "DONE":
                self._square_off(env)
                self._phase = "DONE"
            return

        if t < SCAN_START:
            self._phase = "IDLE"
            return

        if SCAN_START <= t <= ENTRY_HARD_DEADLINE:
            self._capture_open_refs()

        if t < SCAN_END:
            self._phase = "SCANNING" if t < PREVIEW_FROM else "PREVIEW"
            self._plan  = self._build_plan(status="scanning" if t < PREVIEW_FROM else "preview")
            if t >= EARLY_ENTRY_FROM and self._plan and self._plan.sector:
                self._enter_positions(env, early_only=True)
            return

        need_plan = (
            self._plan is None
            or self._plan.status in ("scanning", "preview")
            or (t <= ENTRY_HARD_DEADLINE
                and not (self._plan.sector and self._plan.stocks))
        )
        if need_plan:
            self._plan = self._build_plan(status="final")
            self._phase = "PLANNED"
            if self._plan and self._plan.sector:
                set_selected_stocks(env, self._plan.sector,
                                    [s.symbol for s in self._plan.stocks])
                print(f"[OB] PLAN FINAL | {self._plan.trend.upper()} | sector {self._plan.sector} "
                      f"| {self._plan.direction} | stocks: {[s.symbol for s in self._plan.stocks]}")

        open_ob     = self._count_open_ob(env)
        max_pos     = int(self._p("max_positions"))
        in_primary  = t <= ENTRY_DEADLINE
        ever_traded = self._count_ob_today(env) > 0
        in_extended = (ENTRY_DEADLINE < t <= ENTRY_HARD_DEADLINE) and open_ob == 0 and not ever_traded

        if (in_primary or in_extended) and self._plan and self._plan.sector:
            self._plan.status = "entering"
            self._phase = "ENTERING_EXT" if in_extended else "ENTERING"
            self._enter_positions(env)

        self._manage(env)
        if self._phase not in ("ENTERING", "ENTERING_EXT"):
            self._phase = "MANAGING"

    # ── Public API ────────────────────────────────────────────────────────────

    def _entry_window_open(self) -> bool:
        t = datetime.now().time()
        return SCAN_START <= t <= ENTRY_HARD_DEADLINE

    def get_plan(self) -> dict:
        plan = self._plan or self._build_plan(status="preview")
        if not plan:
            return {"status": "no_data"}
        d = asdict(plan)
        d["phase"]             = self._phase
        d["enabled"]           = self._enabled
        d["entry_window_open"] = self._entry_window_open()
        d["trail_gap_pct"]     = self._p("trail_gap_pct")
        return d

    def get_state(self) -> dict:
        return {
            "enabled":           self._enabled,
            "phase":             self._phase,
            "today":             str(self._today) if self._today else None,
            "open_refs":         len(self._open_ref),
            "entry_window_open": self._entry_window_open(),
            "params":            self.get_params(),
            "windows": {"scan": "09:15–09:40", "entry_by": "09:45", "square_off": "15:15"},
        }


# ── Singleton ─────────────────────────────────────────────────────────────────
opening_breakout = OpeningBreakout()
