"""sector_map.py — Static NSE sector + index membership data.

Edit this file to:
  - Add or remove stocks from the scan universe
  - Change a stock's sector classification
  - Move a stock between NIFTY 50 / Next 50 / Midcap / F&O extras
"""

from typing import Dict, List

# ── Sector classification (symbol → sector) ───────────────────────────────────
SECTOR_OF: Dict[str, str] = {
    # NIFTY 50
    "ADANIENT": "INFRA", "ADANIPORTS": "INFRA", "APOLLOHOSP": "PHARMA",
    "ASIANPAINT": "FMCG", "AXISBANK": "PVT BANK", "BAJAJ-AUTO": "AUTO",
    "BAJFINANCE": "FIN SERVICE", "BAJAJFINSV": "FIN SERVICE", "BEL": "CAPITAL GOODS",
    "BHARTIARTL": "TELECOM", "BPCL": "ENERGY", "BRITANNIA": "FMCG",
    "CIPLA": "PHARMA", "COALINDIA": "ENERGY", "DRREDDY": "PHARMA",
    "EICHERMOT": "AUTO", "GRASIM": "CEMENT", "HCLTECH": "IT",
    "HDFCBANK": "PVT BANK", "HDFCLIFE": "FIN SERVICE", "HEROMOTOCO": "AUTO",
    "HINDALCO": "METAL", "HINDUNILVR": "FMCG", "ICICIBANK": "PVT BANK",
    "INDUSINDBK": "PVT BANK", "INFY": "IT", "ITC": "FMCG", "JSWSTEEL": "METAL",
    "KOTAKBANK": "PVT BANK", "LT": "CAPITAL GOODS", "LTIM": "IT", "M&M": "AUTO",
    "MARUTI": "AUTO", "NESTLEIND": "FMCG", "NTPC": "ENERGY", "ONGC": "ENERGY",
    "POWERGRID": "ENERGY", "RELIANCE": "ENERGY", "SBILIFE": "FIN SERVICE",
    "SBIN": "PSU BANK", "SHRIRAMFIN": "FIN SERVICE", "SUNPHARMA": "PHARMA",
    "TATACONSUM": "FMCG", "TATAMOTORS": "AUTO", "TATASTEEL": "METAL",
    "TCS": "IT", "TECHM": "IT", "TITAN": "FMCG", "TRENT": "RETAIL",
    "ULTRACEMCO": "CEMENT", "WIPRO": "IT",
    # NIFTY NEXT 50
    "ABB": "CAPITAL GOODS", "ADANIENSOL": "ENERGY", "ADANIGREEN": "ENERGY",
    "ADANIPOWER": "ENERGY", "AMBUJACEM": "CEMENT", "DMART": "RETAIL",
    "BAJAJHLDNG": "FIN SERVICE", "BANKBARODA": "PSU BANK", "BERGEPAINT": "FMCG",
    "BOSCHLTD": "AUTO", "CANBK": "PSU BANK", "CHOLAFIN": "FIN SERVICE",
    "COLPAL": "FMCG", "DABUR": "FMCG", "DIVISLAB": "PHARMA", "DLF": "REALTY",
    "GAIL": "ENERGY", "GODREJCP": "FMCG", "HAVELLS": "CONSUMER DURABLES",
    "HAL": "CAPITAL GOODS", "ICICIGI": "FIN SERVICE", "ICICIPRULI": "FIN SERVICE",
    "IOC": "ENERGY", "INDIGO": "AVIATION", "IRFC": "FIN SERVICE",
    "JINDALSTEL": "METAL", "JIOFIN": "FIN SERVICE", "JSWENERGY": "ENERGY",
    "LICI": "FIN SERVICE", "LODHA": "REALTY", "MOTHERSON": "AUTO",
    "NAUKRI": "IT", "PFC": "FIN SERVICE", "PIDILITIND": "CHEMICALS",
    "PNB": "PSU BANK", "RECLTD": "FIN SERVICE", "SIEMENS": "CAPITAL GOODS",
    "SRF": "CHEMICALS", "TATAPOWER": "ENERGY", "TORNTPHARM": "PHARMA",
    "TVSMOTOR": "AUTO", "VBL": "FMCG", "VEDL": "METAL", "ZOMATO": "RETAIL",
    "ZYDUSLIFE": "PHARMA", "GODREJPROP": "REALTY", "POLYCAB": "CAPITAL GOODS",
    "UNITDSPR": "FMCG", "PAGEIND": "FMCG",
    # NIFTY MIDCAP
    "PERSISTENT": "IT", "COFORGE": "IT", "MPHASIS": "IT", "KPITTECH": "IT",
    "OFSS": "IT", "LTTS": "IT", "TATAELXSI": "IT", "PETRONET": "ENERGY",
    "SUZLON": "ENERGY", "IREDA": "ENERGY", "NHPC": "ENERGY", "SJVN": "ENERGY",
    "OIL": "ENERGY", "IGL": "ENERGY", "GUJGASLTD": "ENERGY", "NMDC": "METAL",
    "SAIL": "METAL", "HINDZINC": "METAL", "NATIONALUM": "METAL",
    "APLAPOLLO": "METAL", "BHEL": "CAPITAL GOODS", "CGPOWER": "CAPITAL GOODS",
    "CUMMINSIND": "CAPITAL GOODS", "THERMAX": "CAPITAL GOODS",
    "OBEROIRLTY": "REALTY", "PHOENIXLTD": "REALTY", "PRESTIGE": "REALTY",
    "AUBANK": "PVT BANK", "BANDHANBNK": "PVT BANK", "FEDERALBNK": "PVT BANK",
    "IDFCFIRSTB": "PVT BANK", "RBLBANK": "PVT BANK", "YESBANK": "PVT BANK",
    "INDIANB": "PSU BANK", "UNIONBANK": "PSU BANK", "BANKINDIA": "PSU BANK",
    "IOB": "PSU BANK", "MAZDOCK": "CAPITAL GOODS", "BDL": "CAPITAL GOODS",
    "COCHINSHIP": "CAPITAL GOODS", "LICHSGFIN": "FIN SERVICE",
    "MUTHOOTFIN": "FIN SERVICE", "MFSL": "FIN SERVICE", "SBICARD": "FIN SERVICE",
    "ANGELONE": "FIN SERVICE", "NUVAMA": "FIN SERVICE", "POLICYBZR": "FIN SERVICE",
    "PAYTM": "FIN SERVICE", "LUPIN": "PHARMA", "AUROPHARMA": "PHARMA",
    "ALKEM": "PHARMA", "BIOCON": "PHARMA", "GLENMARK": "PHARMA",
    "LAURUSLABS": "PHARMA", "MANKIND": "PHARMA", "ABBOTINDIA": "PHARMA",
    "MARICO": "FMCG", "TATACOMM": "TELECOM", "IDEA": "TELECOM",
    "INDUSTOWER": "TELECOM", "ASHOKLEY": "AUTO", "BHARATFORG": "AUTO",
    "BALKRISIND": "AUTO", "MRF": "AUTO", "EXIDEIND": "AUTO", "TIINDIA": "AUTO",
    "ESCORTS": "AUTO", "UNOMINDA": "AUTO", "SONACOMS": "AUTO",
    "COROMANDEL": "CHEMICALS", "DEEPAKNTR": "CHEMICALS", "PIIND": "CHEMICALS",
    "UPL": "CHEMICALS", "TATACHEM": "CHEMICALS", "AARTIIND": "CHEMICALS",
    "DALBHARAT": "CEMENT", "ACC": "CEMENT", "RAMCOCEM": "CEMENT",
    "JKCEMENT": "CEMENT", "SHREECEM": "CEMENT", "VOLTAS": "CONSUMER DURABLES",
    "DIXON": "CONSUMER DURABLES", "CROMPTON": "CONSUMER DURABLES",
    "BLUESTARCO": "CONSUMER DURABLES", "KALYANKJIL": "RETAIL",
    "PATANJALI": "FMCG", "INDHOTEL": "HOSPITALITY", "JUBLFOOD": "FMCG",
    "CONCOR": "LOGISTICS", "DELHIVERY": "LOGISTICS", "GMRAIRPORT": "INFRA",
    "IRCTC": "RETAIL", "IRB": "INFRA", "ABCAPITAL": "FIN SERVICE",
    "HUDCO": "FIN SERVICE", "BSE": "FIN SERVICE", "CDSL": "FIN SERVICE",
    "KEI": "CAPITAL GOODS", "SUPREMEIND": "CAPITAL GOODS", "ASTRAL": "CAPITAL GOODS",
    # F&O extras (listed options on NSE, outside NIFTY 200)
    "360ONE": "FIN SERVICE", "AMBER": "CONSUMER DURABLES", "CAMS": "FIN SERVICE",
    "ETERNAL": "RETAIL", "FORCEMOT": "AUTO", "FORTIS": "PHARMA",
    "GODFRYPHLP": "FMCG", "GVT&D": "CAPITAL GOODS", "HDFCAMC": "FIN SERVICE",
    "HINDPETRO": "ENERGY", "HYUNDAI": "AUTO", "IEX": "ENERGY",
    "INOXWIND": "ENERGY", "KAYNES": "CAPITAL GOODS", "KFINTECH": "FIN SERVICE",
    "LTF": "FIN SERVICE", "LTM": "OTHER", "MANAPPURAM": "FIN SERVICE",
    "MAXHEALTH": "PHARMA", "MCX": "FIN SERVICE", "MOTILALOFS": "FIN SERVICE",
    "NAM-INDIA": "FIN SERVICE", "NBCC": "INFRA", "NYKAA": "RETAIL",
    "PGEL": "CAPITAL GOODS", "PNBHOUSING": "FIN SERVICE",
    "POWERINDIA": "CAPITAL GOODS", "PREMIERENE": "ENERGY",
    "RADICO": "FMCG", "RVNL": "INFRA", "SAMMAANCAP": "FIN SERVICE",
    "SOLARINDS": "CHEMICALS", "SWIGGY": "RETAIL", "TMPV": "AUTO",
    "VMM": "RETAIL", "WAAREEENER": "ENERGY",
}

# ── Index membership (symbol lists) ───────────────────────────────────────────
NIFTY50_SYMBOLS = [
    "ADANIENT","ADANIPORTS","APOLLOHOSP","ASIANPAINT","AXISBANK","BAJAJ-AUTO",
    "BAJFINANCE","BAJAJFINSV","BEL","BHARTIARTL","BPCL","BRITANNIA","CIPLA",
    "COALINDIA","DRREDDY","EICHERMOT","GRASIM","HCLTECH","HDFCBANK","HDFCLIFE",
    "HEROMOTOCO","HINDALCO","HINDUNILVR","ICICIBANK","INDUSINDBK","INFY","ITC",
    "JSWSTEEL","KOTAKBANK","LT","LTIM","M&M","MARUTI","NESTLEIND","NTPC","ONGC",
    "POWERGRID","RELIANCE","SBILIFE","SBIN","SHRIRAMFIN","SUNPHARMA","TATACONSUM",
    "TATAMOTORS","TATASTEEL","TCS","TECHM","TITAN","TRENT","ULTRACEMCO","WIPRO",
]

NIFTY_NEXT50_SYMBOLS = [
    "ABB","ADANIENSOL","ADANIGREEN","ADANIPOWER","AMBUJACEM","DMART","BAJAJHLDNG",
    "BANKBARODA","BERGEPAINT","BOSCHLTD","CANBK","CHOLAFIN","COLPAL","DABUR",
    "DIVISLAB","DLF","GAIL","GODREJCP","HAVELLS","HAL","ICICIGI","ICICIPRULI",
    "IOC","INDIGO","IRFC","JINDALSTEL","JIOFIN","JSWENERGY","LICI","LODHA",
    "MOTHERSON","NAUKRI","PFC","PIDILITIND","PNB","RECLTD","SIEMENS","SRF",
    "TATAPOWER","TORNTPHARM","TVSMOTOR","VBL","VEDL","ZOMATO","ZYDUSLIFE",
    "GODREJPROP","POLYCAB","UNITDSPR","PAGEIND",
]

NIFTY_MIDCAP_SYMBOLS = [
    "PERSISTENT","COFORGE","MPHASIS","KPITTECH","OFSS","LTTS","TATAELXSI",
    "PETRONET","SUZLON","IREDA","NHPC","SJVN","OIL","IGL","GUJGASLTD","NMDC",
    "SAIL","HINDZINC","NATIONALUM","APLAPOLLO","BHEL","CGPOWER","CUMMINSIND",
    "THERMAX","OBEROIRLTY","PHOENIXLTD","PRESTIGE","AUBANK","BANDHANBNK",
    "FEDERALBNK","IDFCFIRSTB","RBLBANK","YESBANK","INDIANB","UNIONBANK",
    "BANKINDIA","IOB","MAZDOCK","BDL","COCHINSHIP","LICHSGFIN","MUTHOOTFIN",
    "MFSL","SBICARD","ANGELONE","NUVAMA","POLICYBZR","PAYTM","LUPIN","AUROPHARMA",
    "ALKEM","BIOCON","GLENMARK","LAURUSLABS","MANKIND","ABBOTINDIA","MARICO",
    "TATACOMM","IDEA","INDUSTOWER","ASHOKLEY","BHARATFORG","BALKRISIND","MRF",
    "EXIDEIND","TIINDIA","ESCORTS","UNOMINDA","SONACOMS","COROMANDEL","DEEPAKNTR",
    "PIIND","UPL","TATACHEM","AARTIIND","DALBHARAT","ACC","RAMCOCEM","JKCEMENT",
    "SHREECEM","VOLTAS","DIXON","CROMPTON","BLUESTARCO","KALYANKJIL","PATANJALI",
    "INDHOTEL","JUBLFOOD","CONCOR","DELHIVERY","GMRAIRPORT","IRCTC","IRB",
    "ABCAPITAL","HUDCO","BSE","CDSL","KEI","SUPREMEIND","ASTRAL",
]

NIFTY_FNO_EXTRAS = [
    "360ONE","AMBER","CAMS","ETERNAL","FORCEMOT","FORTIS","GODFRYPHLP","GVT&D",
    "HDFCAMC","HINDPETRO","HYUNDAI","IEX","INOXWIND","KAYNES","KFINTECH","LTF",
    "LTM","MANAPPURAM","MAXHEALTH","MCX","MOTILALOFS","NAM-INDIA","NBCC","NYKAA",
    "PGEL","PNBHOUSING","POWERINDIA","PREMIERENE","RADICO","RVNL","SAMMAANCAP",
    "SOLARINDS","SWIGGY","TMPV","VMM","WAAREEENER",
]

# Pre-computed membership sets
_N50  = set(NIFTY50_SYMBOLS)
_N100 = _N50 | set(NIFTY_NEXT50_SYMBOLS)
_N200 = _N100 | set(NIFTY_MIDCAP_SYMBOLS)
_FNO  = _N200 | set(NIFTY_FNO_EXTRAS)

# Scan universe — every NSE stock with listed options
TRADABLE_INDEX = "FNO"


def _membership(symbol: str) -> List[str]:
    """All indices a symbol belongs to (most specific first)."""
    if symbol in _N50:
        return ["NIFTY50", "NIFTY100", "NIFTY200", "FNO"]
    if symbol in _N100:
        return ["NIFTY100", "NIFTY200", "FNO"]
    if symbol in _N200:
        return ["NIFTY200", "FNO"]
    if symbol in _FNO:
        return ["FNO"]
    return []
