"""strategy.py — EarlyScalp coordinator.

Wires together all ES mixins into one class. This file owns the lifecycle
(start/stop/tick/reset) and the public API (get_plan/get_state).

Do NOT edit this file for filter/entry/management changes — use the dedicated module.
"""

import threading
import time
from dataclasses import asdict
from datetime import datetime, date
from typing import Dict, Optional

from backend.core.market_state   import market
from backend.core.settings_manager import is_live_mode
from backend.core.session_manager  import check_portfolio_sl

from backend.database import TradeEnv

from backend.strategies.es.params  import (
    WARM_START, SCAN_START, ENTRY_START, ENTRY_END, SQUARE_OFF, LOOP_SEC,
)
from backend.strategies.es.params  import ESParamsMixin
from backend.strategies.es.filters import ESFiltersMixin
from backend.strategies.es.state   import ESStateMixin
from backend.strategies.es.entry   import ESEntryMixin
from backend.strategies.es.manage  import ESManageMixin
from backend.strategies.es.exit    import ESExitMixin


class EarlyScalp(ESParamsMixin, ESFiltersMixin, ESStateMixin,
                  ESEntryMixin, ESManageMixin, ESExitMixin):

    def __init__(self):
        self._running  = False
        self._thread: Optional[threading.Thread] = None
        self._enabled  = True
        self._today    = None
        self._open_ref: Dict[str, float] = {}
        self._prev_close: Dict[str, float] = {}
        self._open_ref_final: set = set()
        self._plan = None
        self._phase = "IDLE"
        self._params = self._load_params()
        self._last_candle_time: float = 0
        self._oi_cache: Dict[str, dict] = {}
        # Tick-level entry state
        self._plan_index: Dict[str, object] = {}   # token → ScalpCandidate
        self._entry_callbacks_registered: set = set()
        self._entry_pending: set = set()
        self._trail_locked: Dict[int, float] = {}
        self._trail_armed: Dict[int, bool]   = {}
        self._prev_pnl:    Dict[int, float]  = {}
        self._trail_peak:            Dict[int, float] = {}  # tid → highest premium (₹) at tick level
        self._option_token_to_trade: Dict[str, int]  = {}  # option_token → tid
        self._trade_to_option_token: Dict[int, str]  = {}  # tid → option_token (reverse map)
        self._entry_cache:           Dict[int, float] = {}  # tid → entry_price (for tick-level SL)
        self._symbol_cache:          Dict[int, str]   = {}  # tid → symbol (for WS payloads)
        self._pending_exit:          set              = set()  # tids with in-flight tick-level exit
        self._last_push:             Dict[int, float] = {}  # tid → last WS push monotonic time
        # Portfolio snapshot tracking (in-memory, flushed every 1s by _manage loop)
        self._live_ltp_registry:         Dict[int, float] = {}   # tid → latest option LTP
        self._position_size_cache:       Dict[int, float] = {}   # tid → qty * lot_size
        self._realized_pnl_cache:        float            = 0.0  # sum of closed ES trades today
        self._realized_pnl_cache_seeded: bool             = False
        self._latest_snapshot:           dict             = {}

    # ── Lifecycle ─────────────────────────────────────────────────────────────

    def start(self):
        if self._running:
            return
        self._running = True
        self._thread = threading.Thread(target=self._loop, daemon=True, name="EarlyScalp")
        self._thread.start()
        print("[ES] Early Scalp strategy started.")

    def stop(self):
        self._running = False

    def set_enabled(self, on: bool):
        self._enabled = on

    def _loop(self):
        while self._running:
            try:
                self._tick()
            except Exception as e:
                print(f"[ES] tick error: {e}")
            time.sleep(LOOP_SEC)

    # ── Daily reset ───────────────────────────────────────────────────────────

    def _daily_reset(self, today: date):
        self._today = today
        self._open_ref.clear()
        self._prev_close.clear()
        self._open_ref_final.clear()
        self._plan = None
        self._phase = "IDLE"
        self._last_candle_time = 0
        self._oi_cache.clear()
        self._trail_locked.clear()
        self._trail_armed.clear()
        self._prev_pnl.clear()
        # Unregister all tick callbacks before clearing token maps
        for tok in list(self._option_token_to_trade.keys()):
            market.unregister_tick_callback(tok)
        for tok in list(self._entry_callbacks_registered):
            market.unregister_tick_callback(tok)
        self._entry_callbacks_registered.clear()
        self._entry_pending.clear()
        self._plan_index.clear()
        self._trail_peak.clear()
        self._option_token_to_trade.clear()
        self._trade_to_option_token.clear()
        self._entry_cache.clear()
        self._symbol_cache.clear()
        self._pending_exit.clear()
        self._last_push.clear()
        self._live_ltp_registry.clear()
        self._position_size_cache.clear()
        self._realized_pnl_cache        = 0.0
        self._realized_pnl_cache_seeded = False
        self._latest_snapshot           = {}
        print("[ES] Daily reset complete.")

    # ── Per-tick state machine ────────────────────────────────────────────────

    def _tick(self):
        now = datetime.now()
        t   = now.time()

        if self._today != now.date():
            self._daily_reset(now.date())

        if not self._enabled or not market.is_feed_connected():
            return

        env = TradeEnv.LIVE if is_live_mode() else TradeEnv.PAPER

        if check_portfolio_sl(env):
            self._phase = "KILLED"
            return

        if t >= SQUARE_OFF:
            if self._phase != "DONE":
                self._square_off(env)
                self._phase = "DONE"
                if self._plan:
                    self._plan.status = "done"
            return

        if t < WARM_START:
            self._phase = "IDLE"
            return

        self._capture_open_refs()

        if t < SCAN_START:
            self._phase = "WARMING"
            if self._plan is None or self._plan.status == "idle":
                from backend.strategies.es.types import EarlyScalpPlan
                self._plan = EarlyScalpPlan(
                    status="warming", market_trend="neutral", nifty_move=0.0,
                    note="Capturing 9:15 opening references…",
                    generated_at=now.isoformat()
                )
            return

        if t < ENTRY_START:
            self._phase = "SCANNING"
            self._maybe_refresh_candles(now)
            self._plan = self._build_plan(status="scanning")
            return

        if t <= ENTRY_END:
            self._phase = "ENTERING"
            self._maybe_refresh_candles(now)
            self._plan = self._build_plan(status="entering")
            # Rebuild plan index for tick-level entry lookups
            self._plan_index = {c.token: c for c in self._plan.candidates if c.confirmed}
            # Arm tick callbacks on confirmed candidates (fires order on next tick)
            self._register_entry_callbacks(env)

        self._manage(env)
        if t > ENTRY_END:
            self._phase = "MANAGING"
            # Entry window closed — disarm all entry tick callbacks
            if self._entry_callbacks_registered:
                for tok in list(self._entry_callbacks_registered):
                    market.unregister_tick_callback(tok)
                self._entry_callbacks_registered.clear()
                self._plan_index.clear()
            self._maybe_refresh_candles(now)
            self._plan = self._build_plan(status="managing")

    # ── Public API ────────────────────────────────────────────────────────────

    def get_plan(self) -> dict:
        if not self._plan:
            return {
                "status": "idle", "phase": self._phase,
                "market_trend": "neutral", "nifty_move": 0.0,
                "candidates": [], "note": "Strategy not yet started.",
                "generated_at": "", "params": self.get_params(),
            }
        p = self._plan
        return {
            "status":       p.status,
            "phase":        self._phase,
            "market_trend": p.market_trend,
            "nifty_move":   p.nifty_move,
            "candidates":   [asdict(c) for c in p.candidates],
            "note":         p.note,
            "generated_at": p.generated_at,
            "params":       self.get_params(),
        }

    def get_state(self) -> dict:
        env = TradeEnv.LIVE if is_live_mode() else TradeEnv.PAPER
        return {
            "enabled":        self._enabled,
            "phase":          self._phase,
            "open_positions": self._count_open(env),
            "today":          str(self._today),
        }


# ── Singleton ─────────────────────────────────────────────────────────────────
early_scalp = EarlyScalp()
